### PR TITLE
new: Add the DPD Provider

### PR DESCRIPTION
**Pull request by Snowbaha**
I am adding the DPD pick up. For now it is working until the order, but it is not saving the data.

### CODE REVIEW

**Comment by Snowbaha** [comment]
What is the best way to add the new theme.html without BC yours?
May be, add the chose with theme_dpd.html?

**Comment by loevgaard** [comment]
Hi Julien

Maybe the best approach is make this work in your own app first, so you can make a finished PR? :)

**Comment by Snowbaha** [comment]
Hello, it's working on my side, it's showing the pickup and I can select. But How it is saving this data to get in the dashboard order? Even with your Faker I have no data. I don't understand
image

**Comment by Snowbaha** [comment]
I am close but I am stuck. I don't understand why it is not working. All data are there but it stay "hidden".
I searched someting related to the class `.setono-sylius-pickup-point-label` in the JS file but nothing.

If you can help me.

image
image

**Comment by Snowbaha** [comment]
Hello, I would appreciate to know if you want to help me or not. I can imagine you don't have time but just let me know and I will change my plans.
I spent the morning to understand why the javascript doesn't show the label but I didn't find... I am going to be crazy

**Comment by loevgaard** [comment]
Hi, Julien

I would love to help you out, but for now I don't have the time :(

**Comment by Snowbaha** [comment]
Ok no problem, thank you for your answer. I closed the PR to avoid to lost time on each side. I will do my own path :)

**Comment by igormukhingmailcom** [comment]
@loevgaard I believe we lost label functionality at this point: https://github.com/Setono/SyliusPickupPointPlugin/commit/9c7088de8f3f01d91a853545521c0d1ea2cdd1d7#diff-5a0b3c491b936d8f57a08e16f7d0b4d7cd9555cd1a6d32bbeb1821d10369ba72L5

**Pull request closed without merging**
